Get all species
DEFRA/rod-catch-returns-api-js pull request #28
Opened 2024-10-03 13:10 UTC by ScottDormand96

https://eaflood.atlassian.net/browse/IWTF-4312

Get all species

2024-10-09 07:51 UTC, nabeelamir-defra commented on src/server/routes/__tests__/species.unit.spec.js
> +    it('should return all species with a 200 status code if the call to fetch all species is successful', async () => {
This should say ''should return all species if the call to fetch all species is successful'

2024-10-09 07:56 UTC, nabeelamir-defra approved these changes

2024-10-10 13:12 UTC, jaucourt requested changes

2024-10-10 13:12 UTC, jaucourt commented on src/server/routes/__tests__/species.unit.spec.js
> +      const handler = routes[0].options.handler
Please amend to have `const handler` at the top rather than repeated in every test

2024-10-11 09:51 UTC, jaucourt approved these changes

2024-10-11 09:56 UTC, merged