Update salmon and large adult sea trout
DEFRA/rod-catch-returns-api-js pull request #66
Opened 2024-12-30 13:46 UTC by nabeelamir-defra

https://eaflood.atlassian.net/browse/IWTF-4444

Update salmon and large adult sea trout

2025-01-08 14:29 UTC, jaucourt requested changes

2025-01-08 14:29 UTC, jaucourt commented on src/server/routes/__tests__/catches.integration.spec.js
> +    ]
don't define this as a separate variable, just put in inside the `each` statement

2025-01-08 14:29 UTC, jaucourt commented on src/server/routes/__tests__/catches.integration.spec.js
> +        expected: { kg: 10, oz: 352.739619, type: 'METRIC' }
I think you should probably have an imperial test too

2025-01-08 14:29 UTC, jaucourt commented on src/server/routes/__tests__/catches.integration.spec.js
> +      'should successfully update a catch with a valid $field',
pre-empting the next review comment - if you add a test for imperial mass, you'll have to have an additional description so we don't end up with two tests that have the same description.

2025-01-08 14:29 UTC, jaucourt commented on src/server/routes/__tests__/catches.unit.spec.js
> +      ]
This might be a bit more readable in tabular format: https://jestjs.io/docs/api#2-testeachtablename-fn-timeout

2025-01-20 09:40 UTC, nabeelamir-defra commented on src/schemas/catch.schema.js
> +  const currentDate = new Date()
Thinking about it now and yes it does seem odd. But I had another look at the Java code and that compares the current date too
```
final LocalDate dateCaught = Instant.ofEpochMilli(catchEntry.getDateCaught().getTime()).atZone(ZoneId.systemDefault()).toLocalDate();
        if (dateCaught.isAfter(LocalDate.now())) {
            return handleError(context, "DATE_IN_FUTURE", PROPERTY_DATE_CAUGHT);
        }
```

2025-01-20 10:18 UTC, nabeelamir-defra commented on src/schemas/catch.schema.js
> +    .max(MAX_FISH_MASS_KG)
I have it like this
```
kg: Joi.number()
    .min(MIN_FISH_MASS)
    .max(MAX_FISH_MASS_KG)
    .when('type', {
      is: MEASURES.METRIC,
      then: Joi.required().messages({
        'any.required': 'CATCH_MASS_KG_REQUIRED'
      })
    })
```
and for oz
```
oz: Joi.number()
    .min(MIN_FISH_MASS)
    .max(MAX_FISH_MASS_OZ)
    .when('type', {
      is: MEASURES.IMPERIAL,
      then: Joi.required().messages({
        'any.required': 'CATCH_MASS_OZ_REQUIRED'
      })
    })
```
So it does actually check the min and max regardless of the type. I've just updated it so that it only gets triggered when the type is set.

2025-01-20 11:40 UTC, jaucourt commented on src/schemas/catch.schema.js
> +  const currentDate = new Date()
Ok - please ask Naimulla to check multi-season returns (if he hasn't got this on his list to test already)

2025-01-20 16:08 UTC, jaucourt approved these changes

2025-01-21 09:04 UTC, merged